
> Redhare-Backend@2.0.0 start
> NODE_ENV=production nodemon index.js

[33m[nodemon] 2.0.22[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching path(s): *.*[39m
[33m[nodemon] watching extensions: js,mjs,json[39m
[32m[nodemon] starting `node index.js`[39m
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at errorOrDestroy (node:internal/streams/destroy:238:7)
    at node:internal/fs/streams:272:9
    at FSReqCallback.wrapper [as oncomplete] (node:fs:687:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}

Node.js v20.12.2

> Redhare-Backend@2.0.0 start
> NODE_ENV=production nodemon index.js

[33m[nodemon] 2.0.22[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching path(s): *.*[39m
[33m[nodemon] watching extensions: js,mjs,json[39m
[32m[nodemon] starting `node index.js`[39m
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at errorOrDestroy (node:internal/streams/destroy:238:7)
    at node:internal/fs/streams:272:9
    at FSReqCallback.wrapper [as oncomplete] (node:fs:687:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}

Node.js v20.12.2
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module '/home/user/RedHare-sd-backend/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.12.2

> Redhare-Backend@2.0.0 start
> NODE_ENV=production nodemon index.js

[33m[nodemon] 2.0.22[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching path(s): *.*[39m
[33m[nodemon] watching extensions: js,mjs,json[39m
[32m[nodemon] starting `node index.js`[39m
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at errorOrDestroy (node:internal/streams/destroy:238:7)
    at node:internal/fs/streams:272:9
    at FSReqCallback.wrapper [as oncomplete] (node:fs:687:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}

Node.js v20.12.2
ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT
    at ConnectionManager.connect (/home/user/RedHare-sd-backend/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/home/user/RedHare-sd-backend/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /home/user/RedHare-sd-backend/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/home/user/RedHare-sd-backend/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /home/user/RedHare-sd-backend/node_modules/sequelize/lib/sequelize.js:305:26
    at async MySQLQueryInterface.tableExists (/home/user/RedHare-sd-backend/node_modules/sequelize/lib/dialects/abstract/query-interface.js:102:17)
    at async users.sync (/home/user/RedHare-sd-backend/node_modules/sequelize/lib/model.js:939:21)
    at async Sequelize.sync (/home/user/RedHare-sd-backend/node_modules/sequelize/lib/sequelize.js:377:9) {
  parent: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/home/user/RedHare-sd-backend/node_modules/mysql2/lib/connection.js:205:17)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  original: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/home/user/RedHare-sd-backend/node_modules/mysql2/lib/connection.js:205:17)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  }
}
